### ISSUE TITLE
Could not resolve "deepmerge"

### ISSUE THREAD

**Issue by varunsavaliya** [jamesbrobb/ngx-lightweight-charts#2]
I am facing one issue in this package while staring my project using `npm start`.
`
Could not resolve "deepmerge"

    node_modules/ngx-lightweight-charts/fesm2022/ngx-lightweight-charts.mjs:7:22:
      7 │ import deepmerge from 'deepmerge';
       You can mark the path "deepmerge" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
       D:\Projects\trading-view-frontend-new\node_modules\vite\node_modules\esbuild\lib\main.js:1651
`

Waiting for any help.

**Comment by jamesbrobb** [comment]
I'm presuming you're using the default `npm start` that's set up to run `ng serve` in your  package.json 'scripts'?

deepmerge is a dependency of this library (it's listed in the `peerDependencies` of its package.json) and should have been installed when running `npm install` - so should already be in your `node_modules`.

I'm not sure why that wouldn't be the case, unless possibly you had an error when running `npm install`?

**Comment by jamesbrobb** [comment]
Not sure if this might be the reason?

https://github.com/npm/cli/issues/4934

**Comment by varunsavaliya** [comment]
Yes, this might be the issue. After installing deepmerge it's solved.
but it should be auto-installed because it is a peer dependency of the package.

**Comment by varunsavaliya** [comment]
can you make it compatible with the angular 18 version? Currently, it supports 17 only.

**Comment by jamesbrobb** [comment]
I'm hoping to have a look at creating an v18 version this weekend, i'll let you know once it's done
