### ISSUE TITLE
Issues with Custom Series and Resizing Charts

### ISSUE THREAD

**Issue by sannu3110** [jamesbrobb/ngx-lightweight-charts#3]
Hey @jamesbrobb,  First, I would like to express my appreciation for your library implementation. It has been particularly beneficial for my project, especially in terms of syncing multiple charts. However, I have encountered some issues that are making the library challenging to use:

[Custom Series](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/71030614/4369a8c6-ffa6-46ab-b914-6c48e2a0177f): I am unable to add custom series, specifically HLC (High-Low-Close) series. It would be great if you could provide guidance or an example on how to implement this.

[Resizing Charts](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/71030614/3c0abddc-de40-44c3-9df1-737ccce0ee95): When I add two charts and attempt to resize the first chart by dragging it from the end, I am unable to do so. Is there a way to enable resizing of charts via dragging?

Could you please provide some solutions or examples for the above issues? Your assistance would be greatly appreciated.

Thank you!

![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/71030614/4369a8c6-ffa6-46ab-b914-6c48e2a0177f)
![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/71030614/3c0abddc-de40-44c3-9df1-737ccce0ee95)

**Comment by jamesbrobb** [comment]
Hi,

Do you have any example code showing your implementation so far and where you're getting stuck?

**Comment by sannu3110** [comment]
Hi @jamesbrobb,

I've implemented the custom series, but I'm having trouble passing customSeriesView to the chart since there don't seem to be any available options for it.

![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/71030614/3e0cc6eb-383c-4acf-aa12-14561fc7ef47)

Regarding resizing the chart, I haven't found a way to achieve it.

Looking forward to your response.

Thank you!!

**Comment by jamesbrobb** [comment]
@sannu3110 

I initially built the library for a personal project, which didn't require custom charts, and looking at the code this morning realised that the ability to add a custom series view was missing.

I've now added the additional functionality required to display them, which is currently available in ~~version `0.2.4` only~~ both the latest v17 and v18 releases.

I've added an example showing how to implement the HLCAreaSeries from the [Trading view examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/hlc-area-series) in the [README](https://github.com/jamesbrobb/ngx-lightweight-charts?tab=readme-ov-file#7)

This would definitely be useful as a reusable directive, i'll take a look at implementing something later in the week when i have some spare time, but for now the example should help with what you need.

**Comment by jamesbrobb** [comment]
For the resize, i think you'll need to [look at](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#resize) the `resize` method of the `IChartApi`.

This method is also implemented on `TVChart` so can also be used through its API.

**Comment by varunsavaliya** [comment]
Hello @jamesbrobb ,
I found the same thing (not an issue, it can be a good functionality).
The `resize` method of `IChartApi` is a completely different thing and here the point is resizing the multiple charts means let's say you have 3 charts on the screen and you want to change the heights of charts dynamically using the dragline as @sannu3110  described in the second image. please correct me @sannu3110 if I am wrong here.

**Comment by jamesbrobb** [comment]
Actually looking at this, you don't actually need to touch the chart API at all.

There's an option called [autoSize](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeChartOptions#autosize) which is set to true by default. This tells the chart to automatically (re)render itself depending on the size of its containing element.

So all you need to do is resize the height of the containers and the charts will resize automatically.

**Comment by varunsavaliya** [comment]
Yes, I got your point but, here we're talking about the dynamic heights of charts as shown in the image. 
You can also take reference from [here: ](https://in.tradingview.com/chart/). apply the **Relative Strength Index** indicator and then you will see two charts over there. At the middle of the charts if you hover then you'll find a horizontal line to adjust the **height of the charts** according to you.

**Comment by jamesbrobb** [comment]
This would accomplish it https://angular-split.github.io/examples/min-max-split
