### ISSUE TITLE
Crosshair Synchronization:

### ISSUE THREAD

**Issue by varunsavaliya** [jamesbrobb/ngx-lightweight-charts#4]
As you can see in the attached video, the crosshair is not synchronized correctly on the last data point. This issue causes the crosshair to behave inconsistently, which affects the accuracy and usability of the chart.

https://github.com/jamesbrobb/ngx-lightweight-charts/assets/122857288/bd93fd86-647c-4780-baed-a82061ca63d9

**Comment by jamesbrobb** [comment]
Thanks, this is fixed in the latest version

**Comment by jamesbrobb** [comment]
There are a couple of things to be aware of though, that are issues that you'd need to raise on the `lightweight-charts` [github](https://github.com/tradingview/lightweight-charts) if you require them to be fixed.

If you mouseover the following synced chart [example](https://tradingview.github.io/lightweight-charts/tutorials/how_to/set-crosshair-position) and then scroll, you'll see the crosshair move to either the left or right hand side of the chart (depending) on which way you scroll.

Unfortunately the only way to 'fix' this issue, causes an issue if you scroll off the end of a chart and then scroll back on again

https://github.com/jamesbrobb/ngx-lightweight-charts/assets/1752245/3609b68d-21af-4ed3-938c-d512bf8fbe18
